### ISSUE TITLE
test.py has no test.jpg image in dataset

### ISSUE THREAD

**Issue by hasti7962** [huoxiangzuo/HiFuse#11]
thanks with courage 
I have problem to use this project as my own here is the problem 
there is no test.jpg found on dataset ISI2018 that needed to be pathed in line 23 in test.py file
where I can found this image or how to replace it with another. 
what properties needed that I must considered for that image ?

**Comment by huoxiangzuo** [comment]
The test.py file here is only used as a test demo for a single image. You can select any image you want to classify.
