### ISSUE TITLE
网络的评价指标

### ISSUE THREAD

**Issue by Dreamboatmq** [huoxiangzuo/HiFuse#13]
阅读您发表的HiFuse这篇文章后，收获很多，在评估模型时出现了一些问题，期待您能回复。
请问您可以提供最终评估模型的脚本吗？具体来说就是写一个评估脚本，加载模型训练权重，加载整个测试集用于评估。获得各项评估指标如：准确率，F1，精确度，召回率等等。您的test.py仅仅是用于测试单张图片属于各个类别的概率。

**Comment by huoxiangzuo** [comment]
已收到您的邮件，感谢您对我们的工作感兴趣！这里的demo仅供参考学习，为保证公平，训练及测试均在mmcv环境下进行。如果您想在demo下批量测试指标，建议参考主页中的SPA项目的test代码进行改进。

**Comment by Dreamboatmq** [comment]
非常感谢您的回复，问题已经解决，再次感谢~

**Comment by jiaoxueping** [comment]
您好，请问我用了文章中所说的ISIC2018数据集进行了本模型训练，评估的时候评估指标达不到论文中所说的结果是怎么回事，有什么修改建议吗

**Comment by huoxiangzuo** [comment]
> 您好，请问我用了文章中所说的ISIC2018数据集进行了本模型训练，评估的时候评估指标达不到论文中所说的结果是怎么回事，有什么修改建议吗

根据您提供的信息，无法给出具体建议，以您所复现的环境为准。
