### ISSUE TITLE
Some problems of unstable training results

### ISSUE THREAD

**Issue by denghuowj** [huoxiangzuo/HiFuse#2]
您好，我在复现您代码时遇到了训练结果波动很大的问题，请问训练结果的不稳定您是怎么解决的。
另外我尝试了mmengine，但是无法调用gpu训练，您有遇到过这方面问题吗

**Comment by huoxiangzuo** [comment]
很高兴您对我们的工作感兴趣。
回答1：训练结果有些许波动属于正常现象。如果波动较大，请检查您是否设定了合适的学习率和batchsize，其他模型是否出现了同样的问题？此外，您需要注意数据集的划分，可以设定随机种子以稳定训练结果。如果可以，请提供训练的log，以便我们分析排查问题所在。
回答2：mmengine无法调用gpu，您需要设置device=‘cuda’。如果未解决，您可能需要进一步学习mmcv相关知识，可以到mm社区获得更详尽的答案。

**Comment by denghuowj** [comment]
> 很高兴您对我们的工作感兴趣。 回答1：训练结果有些许波动属于正常现象。如果波动较大，请检查您是否设定了合适的学习率和batchsize，其他模型是否出现了同样的问题？此外，您需要注意数据集的划分，可以设定随机种子以稳定训练结果。如果可以，请提供训练的log，以便我们分析排查问题所在。 回答2：mmengine无法调用gpu，您需要设置device=‘cuda’。如果未解决，您可能需要进一步学习mmcv相关知识，可以到mm社区获得更详尽的答案。

好的 感谢您的解答
