### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by YCheno** [huoxiangzuo/HiFuse#7]
Hi, I have finished training proces, but when I run test.py, it has the following error:
Traceback (most recent call last):
  File "E:/HiFuse-main/test.py", line 68, in <module>
    main()
  File "E:/HiFuse-main/test.py", line 45, in main
    model.load_state_dict(torch.load(model_weight_path, map_location=device))
  File "D:\Anaconda3\envs\pyt1.10\lib\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for main_model:
	Unexpected key(s) in state_dict: "stages.2.2.dwconv.weight", "stages.2.2.dwconv.bias", "stages.2.2.norm.weight", "stages.2.2.norm.bias", "stages.2.2.pwconv.weight", "stages.2.2.pwconv.bias", "stages.2.3.dwconv.weight", "stages.2.3.dwconv.bias", "stages.2.3.norm.weight", "stages.2.3.norm.bias", "stages.2.3.pwconv.weight", "stages.2.3.pwconv.bias", "stages.2.4.dwconv.weight", "stages.2.4.dwconv.bias", "stages.2.4.norm.weight", "stages.2.4.norm.bias", "stages.2.4.pwconv.weight", "stages.2.4.pwconv.bias", "stages.2.5.dwconv.weight", "stages.2.5.dwconv.bias", "stages.2.5.norm.weight", "stages.2.5.norm.bias", "stages.2.5.pwconv.weight", "stages.2.5.pwconv.bias", "layers3.blocks.2.norm1.weight", "layers3.blocks.2.norm1.bias", "layers3.blocks.2.attn.relative_position_bias_table", "layers3.blocks.2.attn.relative_position_index", "layers3.blocks.2.attn.qkv.weight", "layers3.blocks.2.attn.qkv.bias", "layers3.blocks.2.attn.proj.weight", "layers3.blocks.2.attn.proj.bias", "layers3.blocks.2.norm2.weight", "layers3.blocks.2.norm2.bias", "layers3.blocks.2.fc1.weight", "layers3.blocks.2.fc1.bias", "layers3.blocks.3.norm1.weight", "layers3.blocks.3.norm1.bias", "layers3.blocks.3.attn.relative_position_bias_table", "layers3.blocks.3.attn.relative_position_index", "layers3.blocks.3.attn.qkv.weight", "layers3.blocks.3.attn.qkv.bias", "layers3.blocks.3.attn.proj.weight", "layers3.blocks.3.attn.proj.bias", "layers3.blocks.3.norm2.weight", "layers3.blocks.3.norm2.bias", "layers3.blocks.3.fc1.weight", "layers3.blocks.3.fc1.bias", "layers3.blocks.4.norm1.weight", "layers3.blocks.4.norm1.bias", "layers3.blocks.4.attn.relative_position_bias_table", "layers3.blocks.4.attn.relative_position_index", "layers3.blocks.4.attn.qkv.weight", "layers3.blocks.4.attn.qkv.bias", "layers3.blocks.4.attn.proj.weight", "layers3.blocks.4.attn.proj.bias", "layers3.blocks.4.norm2.weight", "layers3.blocks.4.norm2.bias", "layers3.blocks.4.fc1.weight", "layers3.blocks.4.fc1.bias", "layers3.blocks.5.norm1.weight", "layers3.blocks.5.norm1.bias", "layers3.blocks.5.attn.relative_position_bias_table", "layers3.blocks.5.attn.relative_position_index", "layers3.blocks.5.attn.qkv.weight", "layers3.blocks.5.attn.qkv.bias", "layers3.blocks.5.attn.proj.weight", "layers3.blocks.5.attn.proj.bias", "layers3.blocks.5.norm2.weight", "layers3.blocks.5.norm2.bias", "layers3.blocks.5.fc1.weight", "layers3.blocks.5.fc1.bias". 
I want to know what is the reason, thank you!

**Comment by huoxiangzuo** [comment]
You can change 'checkpoint' to 'model.state dict()' in train.py (line 140).

**Comment by YCheno** [comment]
Thanks for your reply, but it doesn't work. In test.py, "best_model.pth" is used, and in train.py,  when save  "best_model.pth", it is "torch.save(model.state_dict(), "./model_weight/best_model.pth") "(line 125). Hence, I don't think that's the reason.

**Comment by YCheno** [comment]
> You can change 'checkpoint' to 'model.state dict()' in train.py (line 140).

Thanks for your reply, but it doesn't work. In test.py, "best_model.pth" is used, and in train.py, when save "best_model.pth", it is "torch.save(model.state_dict(), "./model_weight/best_model.pth") "(line 125). Hence, I don't think that's the reason.

**Comment by YCheno** [comment]
> You can change 'checkpoint' to 'model.state dict()' in train.py (line 140).

And I tried "model.load_state_dict(torch.load(model_weight_path, map_location=device),False)", it can run， but I wonder if the model is really loaded, because the accuracy in test was ten points lower than that in training phase.

**Comment by YCheno** [comment]
> You can change 'checkpoint' to 'model.state dict()' in train.py (line 140).

I have found the reason. in train.py is "from main_model import HiFuse_Small as create_model" but in test.py is "from main_model import main_model as create_model", the model is different.
