### ISSUE TITLE
Why have 2 sigmoid function in channel attention of HFF block?

### ISSUE THREAD

**Issue by mxmm2123** [huoxiangzuo/HiFuse#9]
Hi author. In HFF block, i see you use 2 sigmoid function in channel attention, what is the purpose here?
```
# channel attetion for transformer branch
g_jump = g
max_result=self.maxpool(g)
avg_result=self.avgpool(g)
max_out=self.se(max_result)
avg_out=self.se(avg_result)
output=self.sigmoid(max_out+avg_out) # first sigmoid func
g = self.sigmoid(output) * g_jump    # 2 sigmoid function in here?
```
i reference channel attention module in [CBAM model](https://github.com/Jongchan/attention-module/blob/5d3a54af0f6688bedca3f179593dff8da63e8274/MODELS/cbam.py#L26) it don't have second sigmoid func.

**Comment by huoxiangzuo** [comment]
Thank you for your careful discovery of the error. It is correct to use sigmoid once and we have made changes in this regard. I don't know how to explain it, because using it twice did not cause a decrease in accuracy, which is very metaphysical.
